### ISSUE TITLE
Broken with latest Visual Studio 2022 Update to 17.2.6

### ISSUE THREAD

**Issue by PhilippPaetzold** [notpeelz/VersionInfoGenerator#3]
Since I updated to 17.2.6 I can not compile projects that make use of VersionInfoGenerator 2.1.3 anymore. I get errors like this:

```shell
Roeber.Tools.LogViewer\VersionInfoGenerator\VersionInfoGenerator.VersionInfoGenerator\Roeber.Tools.LogViewer_jgej3tc1_wpftmp.VersionInfo.cs(8,27,8,38): error CS0101: The namespace "Roeber.Tools.LogViewer_jgej3tc1_wpftmp" already contains a definition for "VersionInfo".
Roeber.Tools.LogViewer\VersionInfoGenerator\VersionInfoGenerator.VersionInfoGenerator\Roeber.Tools.LogViewer_jgej3tc1_wpftmp.VersionInfo.cs(6,6,6,19): error CS0579: Double attribute "GeneratedCode".
Roeber.Tools.LogViewer\VersionInfoGenerator\VersionInfoGenerator.VersionInfoGenerator\Roeber.Tools.LogViewer_jgej3tc1_wpftmp.VersionInfo.cs(7,6,7,23): error CS0579:  Double attribute "CompilerGenerated".
```

With previous versions of Visual Studio 2022 it compiles just fine.

I tried full clean, rebuild, reload of VS and also building with command-line "dotnet build".

Attached is a small WPF-Testapplication which I can not compile.

[TestWpf.zip](https://github.com/notpeelz/VersionInfoGenerator/files/9206076/TestWpf.zip)

**Comment by notpeelz** [comment]
Looks like you've hit this issue: https://github.com/dotnet/wpf/issues/6792

This should be fixed once .NET 6.0.9 lands. You can get an idea for their release schedule here: https://github.com/dotnet/core/tree/main/release-notes/6.0

In the meantime, I pushed v2.1.4 which incorporates [the suggested workaround](https://github.com/dotnet/core/blob/8efba8ffcc21518ca28fb7e9a33a721aa53826ea/release-notes/6.0/known-issues.md#issues-building-wpf-application-with-windows-desktop-607-and-608).
